name: Security Pipeline

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:

# ---------------- BUILD ----------------
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Build Verification
        run: python -m py_compile app/app.py


# ---------------- UNIT TESTS ----------------
  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Tests
        run: pytest


# ---------------- SEMGREP SAST ----------------
  semgrep:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep Scan
        run: semgrep --config=auto


# ---------------- DEPENDENCY SCAN ----------------
  dependency_scan:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Install pip-audit
        run: pip install pip-audit

      - name: Run Dependency Scan
        run: pip-audit


# ---------------- GITLEAKS ----------------
  gitleaks:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2


# ---------------- TRUFFLEHOG ----------------
  trufflehog:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@main


# ---------------- SECURITY GATE ----------------
  security_gate:
    runs-on: ubuntu-latest
    needs: [test, semgrep, dependency_scan, gitleaks, trufflehog]

    steps:
      - name: Security Gate
        run: echo "All security checks passed"


# ---------------- DEPLOY TO EC2 ----------------
  deploy:
    runs-on: ubuntu-latest

    needs: [security_gate]

    steps:

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy Application
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/secure-capstone-project
            git pull origin main
            sudo systemctl start app
